apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: numen-games
resources:
  - ../org-config/overlays/pro
  - ../christian/pro
  - ../carlo/pro
  - ../engage/pro
  - ../experience/pro
  - ../ghost/pro
  - ../kevinonearth/pro
  - ../maria/pro
  - ../pablofm/pro
  - ../r3s3t/pro
  - ../training/pro
  - ../argent/pro
  - ../ath21/pro
  - ../fernandobarrientos/pro
  - ../spinosound/pro
  - ../tetuanvalley/pro
  - ../escueladelvidrio/pro
  - ../nes/pro
  - ../clio/pro
  - ../devstarlight/pro
  - ../dani/pro
  - ../backfund/pro
  - ../tramontana/pro
  - ../curiocards/pro
  - ../mab/pro
  - ../homestudio/pro
  - ../miirror/pro
  - ../arcasiles/pro
  - ../b0gie/pro
  - ../mmerge/pro
  - ../theculturalcyberhive/pro
  - ../omka/pro
  - ../teresamadruga/pro
  - ../chess/pro
  - ../cpl121/pro
  - ../juliaux/pro
  - ../alejandraux/pro