apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: numen-games-pre
resources:
  - ../org-config/overlays/pre
  - ../christian/pre
  - ../carlo/pre
  - ../engage/pre
  - ../experience/pre
  - ../ghost/pre
  - ../kevinonearth/pre
  - ../maria/pre
  - ../pablofm/pre
  - ../r3s3t/pre
  - ../training/pre
  - ../argent/pre
  - ../ath21/pre
  - ../fernandobarrientos/pre
  - ../spinosound/pre
  - ../tetuanvalley/pre
  - ../escueladelvidrio/pre
  - ../nes/pre
  - ../clio/pre
  - ../devstarlight/pre
  - ../dani/pre
  - ../backfund/pre
  - ../tramontana/pre
  - ../curiocards/pre
  - ../mab/pre
  - ../homestudio/pre
  - ../miirror/pre
  - ../arcasiles/pre
  - ../b0gie/pre
  - ../mmerge/pre
  - ../theculturalcyberhive/pre
  - ../omka/pre
  - ../teresamadruga/pre
  - ../chess/pre
  - ../cpl121/pre
  - ../juliaux/pre
  - ../alejandraux/pre
  - ../portfolio/pre
  - ../museodelvidrio/pre