apiVersion: v1
kind: ConfigMap
metadata:
  name: museodelvidrio-pre-values
  namespace: numen-games-pre
  annotations:
    config-version: "1.0.0"
data:
  values.yaml: |
    awsSecretName: "hyperfy2-numen-games-museo-del-vidrio-pre"
    orgName: "numen-games"
    appName: "museodelvidrio"
    environment: "pre"
    namespace: numen-games-pre
    serviceAccountName: "numen-games-pre"
    image:
      repository: "ghcr.io/numengames/numinia-hyperfy2"
      tag: "dev"
    world: "pre-museodelvidrio"
    publicMaxUploadSize: "2000"
    publicWsUrl: "wss://pre.museodelvidrio.numen.games/ws"
    publicApiUrl: "https://pre.museodelvidrio.numen.games/api"
    assetsBaseUrl: "https://statics.numinia.xyz/hyperfy-spaces/numen-games/museodelvidrio/dev/assets"
    clean: "true"
    tlsSecretName: "numen-games-tls"
    resources:
      requests:
        cpu: "256m"
        memory: "256Mi"
      limits:
        cpu: "512m"
        memory: "1024Mi"
    autoscaling:
      minScale: 0
      maxScale: 1
    domainMapping:
      enabled: true
      hostname: pre.museodelvidrio.numen.games
      namespace: numen-games-pre