apiVersion: v1
kind: ConfigMap
metadata:
  name: alejandraux-pro-values
  namespace: numen-games
  annotations:
    config-version: "1.0.0"
data:
  values.yaml: |
    awsSecretName: "hyperfy2-numen-games-alejandraux-pro"
    orgName: "numen-games"
    appName: "alejandraux"
    environment: "pro"
    namespace: numen-games
    serviceAccountName: "numen-games"
    world: "pro-alejandraux"
    publicMaxUploadSize: "1"
    publicWsUrl: "wss://alejandraux.numen.games/ws"
    publicApiUrl: "https://alejandraux.numen.games/api"
    assetsBaseUrl: "https://statics.numinia.xyz/hyperfy-spaces/numen-games/alejandraux/latest/assets"
    collectionsBaseUrl: "https://statics.numinia.xyz/hyperfy-spaces/numen-games/collections/dev"
    clean: "true"
    tlsSecretName: "numen-games-tls"
    resources:
      requests:
        cpu: "256m"
        memory: "256Mi"
      limits:
        cpu: "512m"
        memory: "1024Mi"
    autoscaling:
      minScale: 0
      maxScale: 1
    domainMapping:
      enabled: true
      hostname: alejandraux.numen.games
      namespace: numen-games