apiVersion: v1
kind: ConfigMap
metadata:
  name: juliaux-pre-values
  namespace: numen-games-pre
  annotations:
    config-version: "1.0.0"
data:
  values.yaml: |
    awsSecretName: "hyperfy2-numen-games-juliaux-pre"
    orgName: "numen-games"
    appName: "juliaux"
    environment: "pre"
    namespace: numen-games-pre
    serviceAccountName: "numen-games-pre"
    world: "pre-juliaux"
    publicMaxUploadSize: "2000"
    publicWsUrl: "wss://pre.juliaux.numen.games/ws"
    publicApiUrl: "https://pre.juliaux.numen.games/api"
    assetsBaseUrl: "https://statics.numinia.xyz/hyperfy-spaces/numen-games/juliaux/dev/assets"
    collectionsBaseUrl: "https://statics.numinia.xyz/hyperfy-spaces/numen-games/collections/dev"
    clean: "true"
    tlsSecretName: "numen-games-tls"
    resources:
      requests:
        cpu: "256m"
        memory: "256Mi"
      limits:
        cpu: "2048m"
        memory: "4096Mi"
    autoscaling:
      minScale: 0
      maxScale: 1
    domainMapping:
      enabled: true
      hostname: pre.juliaux.numen.games
      namespace: numen-games-pre